[build]
  publish = "."
  command = "sed -i \"s/YOUR_POSTHOG_KEY/${POSTHOG_PROJECT_KEY}/g\" index.html"

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
